### ISSUE TITLE
Addon Manager Doesn't Manage ConfigMaps

### ISSUE THREAD

**Issue by rossedman** [Azure/acs-engine#1089]
**Is this a request for help?**: 

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: Latest

---

Kubernetes 1.6.6

**What happened**: Addon Manager does not support management of ConfigMaps

**What you expected to happen**: Addon Manager to manage my ConfigMap

**How to reproduce it** (as minimally and precisely as possible): Add a config map to the `/etc/kubernetes/addons` folder and then it never gets created

**Anything else we need to know**: 

Only used one master, inserted file into addon directory. All other files I inserted are picked up and managed except for the ConfigMap.

This feature was completed and added to addon-manager [quite some time ago](https://github.com/kubernetes/kubernetes/issues/32329). It appears that ACS is using the latest version of addon manager but its a container managed separately by azure

Here is an example of the config map used:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: "Reconcile"
data:
  filebeat.yml:
    filebeat.registry_file: /var/log/containers/filebeat_registry
    fields_under_root: true
    fields:
      host.region: eastus2
      host.resource-group: my-resource-group
      host.environment: mgmt

    filebeat.prospectors:
    - paths:
      - "/var/log/containers/*.log"
      symlinks: true
      json.message_key: log
      json.keys_under_root: true
      json.add_error_key: true
      multiline.pattern: '^\s'
      multiline.match: after
      document_type: kubelogs
      fields:
        host.name: ${FILEBEAT_HOST}
      fields_under_root: true

    #
    # NOTICE: the hosts array must be set to the same name and port
    # as the above elastic settings to be reachable
    #
    output.elasticsearch:
      hosts: ["http://elastic-logging:9200"]
      timeout: 15
      index: "mgmt-%{+yyyy.MM.dd}"
      pipeline: kubelogs

    logging.level: ${LOG_LEVEL:error}
```
