### ISSUE TITLE
Wrong configuration item found in ~/.kube/config

### ISSUE THREAD

**Issue by micli** [Azure/acs-engine#1261]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Yes ISSUE
---

**What version of acs-engine?**:
V0.4.0 and V0.5.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
I used acs-engine CLI and Kubernetes.json sample file to create a k8s on Azure mooncake. When I used scp copied kubectl config file to local, I found that there was a wrong URL in config file like below:
---
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ""
    server: **https://acstestmicl.chinanorth.cloudapp.azure.com**
  name: "acstestmicl"
contexts:
- context:
    cluster: "acstestmicl"
    user: "acstestmicl-admin"
  name: "acstestmicl"
current-context: "acstestmicl"
kind: Config
users:
- name: "acstestmicl-admin"
......
```
The k8s server URL is weird. It looks like combined Global cloud service with china location. 
When you install a image it would let you see below error message:
> kubectl run nginx --image nginx
error: failed to discover supported resources: Get https://acstestmicl.chinanorth.cloudapp.azure.com/api: dial tcp: lookup acstestmicl.chinanorth.cloudapp.azure.com on 10.222.220.5:53: no such host

**What you expected to happen**:
The k8s server URL should be: acstestmicl.chinanorth.cloudapp.chinacloudapi.cn in config file.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
Actually, acs-engine cannot support k8s cluster creation on Azure Mooncake. I think acs-engine should add a parameter to claim which Azure service should use. It would be useful for US gov and Berlin in future.
