### ISSUE TITLE
AzureFile fails to mount

### ISSUE THREAD

**Issue by avaranovich** [Azure/acs-engine#168]
I cannot make AzureFile mount to work for pod.
If I ssh into a master, and try to mount a local folder
`sudo mount -t cifs //accname.file.core.windows.net/test ./test -o vers=3.0,username=accname,password=base64pwd,dir_mode=0777,file_mode=0777`
it works.

Hovewer, if I try to follow this example
https://github.com/kubernetes/kubernetes/blob/master/examples/volumes/azure_file/README.md

I am getting a "permission error" message
`MountVolume.SetUp failed for volume "kubernetes.io/azure-file/1fb73f42-d75e-11e6-b642-000d3a27f4b0-mypd" (spec.Name: "mypd") pod "1fb73f42-d75e-11e6-b642-000d3a27f4b0" (UID: "1fb73f42-d75e-11e6-b642-000d3a27f4b0") with: mount failed: exit status 32 Mounting arguments: //00kakbvmlsrp7geagnt0.file.core.windows.net/test /var/lib/kubelet/pods/1fb73f42-d75e-11e6-b642-000d3a27f4b0/volumes/kubernetes.io~azure-file/mypd cifs [vers=3.0,username=00kakbvmlsrp7geagnt0,password=52�Ԋx��~k�I�&�e�F={�:j��� �Jp�$���d��p^�g�ے�吞L��LKE�/�,dir_mode=0777,file_mode=0777] Output: mount error(13): Permission denied Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)` 

The file share is in the same location as VM, as it is also verified by the mounting via SSH. I am not sure if this is a kubernetes issue, or something related to ACS Ubuntu version or other configuration

**Comment by colemickens** [comment]
Can you please post your yaml file?

**Comment by avaranovich** [comment]
```
azure-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: MDBrYWtidm1sc3JwN2dlYWdudDA=
  azurestorageaccountkey: base64accountkey==
```

azure.yaml

```
apiVersion: v1
kind: Pod
metadata:
 name: azure
spec:
 containers:
  - image: kubernetes/pause
    name: azure
    volumeMounts:
      - name: azure
        mountPath: /mnt/azure
 volumes:
      - name: azure
        azureFile:
          secretName: azure-secret
          shareName: test
          readOnly: false
```
