### ISSUE TITLE
Impossible to create a LoadBalancer

### ISSUE THREAD

**Issue by AlexGrs** [Azure/acs-engine#194]
I have the following error message:

```
2017-01-19T14:00:05.160701452Z E0119 14:00:05.160531       1 servicecontroller.go:760] Failed to process service. Retrying in 5m0s: Failed to create load balancer for service default/testlb: network.SecurityGroupsClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=parameters.SecurityGroupPropertiesFormat.Subnets constraint=ReadOnly value=[]network.Subnet{network.Subnet{Response:autorest.Response{Response:(*http.Response)(nil)}, ID:(*string)(0xc421cd6330), SubnetPropertiesFormat:(*network.SubnetPropertiesFormat)(nil), Name:(*string)(nil), Etag:(*string)(nil)}} details: readonly parameter; must send as nil or empty in request
```

My services definition is the following:

```
---
apiVersion: v1
kind: Service
metadata:
  name: testlb
  labels:
    run: testlb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: testlb-http
    protocol: TCP
    targetPort: 12000
  - port: 443
    name: testlb-https
    protocol: TCP
  selector:
    app: testlb
```

Any idea what could be the cause ?
