### ISSUE TITLE
upgrade k8s process is broke

### ISSUE THREAD

**Issue by jalberto** [Azure/acs-engine#2022]
**Is this a request for help?**:
yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.11
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
1.7.6 -> 1.8.4

**What happened**:

Running:

```
acs-engine upgrade \
  --subscription-id xxx \
  --deployment-dir ./_output/xxx \
  --location westeurope \
  --resource-group xxx \
  --upgrade-version 1.8.4 \
  --auth-method client_secret \
  --client-id xxx \
  --client-secret xxx
```

got:

```
[...]
INFO[0138] Master pool set count to: 1 temporarily during upgrade...
 
INFO[0138] Starting ARM Deployment (master-18-01-10T13.40.08-1740684113). This will take some time... 
INFO[0166] Finished ARM Deployment (master-18-01-10T13.40.08-1740684113). 
INFO[0166] Error creating upgraded master VM: k8s-master-11577755-0 
FATA[0166] Error upgrading cluster: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." 
```

In azure portal:

![screenshot from 2018-01-10 13-44-01](https://user-images.githubusercontent.com/99927/34773709-f53120e0-f60c-11e7-8f28-794cfe5f2487.png)

**What you expected to happen**:
Upgrade cluster without errors

**How to reproduce it** (as minimally and precisely as possible):

Follow upgrade docs: https://github.com/Azure/acs-engine/tree/master/examples/k8s-upgrade

**Anything else we need to know**:

I am using vnet peering configured in azure portal, not using custom vnets

This actually left my cluster in bad shape, so is quite urgent.

**Comment by jalberto** [comment]
Is this a technical limitation or a non-implemented feature?

Probably 'upgrade' command must check for this commons pitfalls and throw a warning before being the process.

**Comment by jalberto** [comment]
Testing if deleting peering make it works, and it does but it takes quite long to upgrade a single master, and even more to the upgrade command to notice deployment has finished as it continues stuck in:

```
INFO[0210] Starting ARM Deployment (master-18-01-11T12.56.22-617391183). This will take some time...
```

![screenshot from 2018-01-11 14-08-57](https://user-images.githubusercontent.com/99927/34827008-075f335c-f6d9-11e7-9cad-3763de49e669.png)

Meanwhile because of previous error, now there is not leader, so whole cluster is unusable.

**Comment by jalberto** [comment]
as expected now ther is this:

```
INFO[4992] Master VM: k8s-master-11577755-1 status error: client: etcd cluster is unavailable or misconfigured; error #0: client: etcd member http://127.0.0.1:2379 has no leader
```

So now what?

I already opened a cirticual issue in azure support but no one seems to be taking care of this.

**Comment by jalberto** [comment]
so after several retyes every master get updated but any `kubectl` command get a `i/o timeout` 

any clue will be welcome

**Comment by jalberto** [comment]
Dear diary, 3 days since The incident and not I already lost any hope for help. Seems like this place is more isolated every day.
Now seem like upgrade broke CNI (calico) in some way and nor etcd nor k8s services will start

**Comment by jalberto** [comment]
more funny stuff:

```
-- Unit etcd.service has begun starting up.                                                                                                                                     
Jan 11 18:31:17 k8s-master-11577755-0 systemd[22069]: etcd.service: Failed at step EXEC spawning /usr/bin/etcd: No such file or directory                                       
-- Subject: Process /usr/bin/etcd could not be executed
```

**Comment by brendandburns** [comment]
Can you do an `ls /usr/bin/etcd`, also can you look at /var/log/cloud-init.log and see if cloud-init is correctly  installing/running?

**Comment by jalberto** [comment]
@brendanburns I was investigating etcd when I found is not instaled, so I tried to install ti acs-engine way:

```
root@k8s-master-11577755-0:~# /opt/azure/containers/setup-etcd.sh                                                                                                               
+ ETCD_VER=v2.5.2                           
+ DOWNLOAD_URL=https://acs-mirror.azureedge.net/github-coreos                           
+ mkdir -p /tmp/etcd-download               
+ curl -L https://acs-mirror.azureedge.net/github-coreos/etcd-v2.5.2-linux-amd64.tar.gz -o /tmp/etcd-v2.5.2-linux-amd64.tar.gz                                                  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current         
                                 Dload  Upload   Total   Spent    Left  Speed           
100   215  100   215    0     0     74      0  0:00:02  0:00:02 --:--:--    74          
+ tar xzvf /tmp/etcd-v2.5.2-linux-amd64.tar.gz -C /usr/bin/ --strip-components=1        

gzip: stdin: not in gzip format             
tar: Child returned status 1                
tar: Error is not recoverable: exiting now  
+ useradd -U etcd                           
useradd: user 'etcd' already exists         
++ head -c 32 /dev/urandom                  
++ base64                                   
+ usermod -p 5ICuQ0258U/OBqze1SjjZi8g+9+/pSL0LtkG7nquQbU= etcd                          
sent invalidate(passwd) request, exiting    
sent invalidate(group) request, exiting     
sent invalidate(passwd) request, exiting    
sent invalidate(group) request, exiting     
+ passwd -u ''                              
passwd: user '' does not exist              
+ systemctl daemon-reload                   
+ systemctl enable etcd.service             
Failed to execute operation: Invalid argument
```

```
root@k8s-master-11577755-0:~# cat /tmp/etcd-v2.5.2-linux-amd64.tar.gz
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:02f5e54f-001e-008b-390e-8b5fd6000000
Time:2018-01-11T18:59:05.6635280Z</Message></Error>
```

lots of fun

**Comment by brendandburns** [comment]
What version of acs-engine are you using?

Thanks

**Comment by jalberto** [comment]
@brendanburns 0.11

**Comment by jalberto** [comment]
I actually cannot find an official 2.5.2 release:

![screenshot from 2018-01-11 20-38-51](https://user-images.githubusercontent.com/99927/34843714-8bc02b34-f70f-11e7-8559-7ea5fee3aee4.png)

**Comment by jackfrancis** [comment]
Hi @jalberto could you try to modify the `/opt/azure/containers/setup-etcd.sh` script to change the assignment of `ETCD_VER` to v2.3.7?

**Comment by jalberto** [comment]
I have doubts, Why not latest 3.x version? (I don't want to mess it more)

**Comment by jackfrancis** [comment]
I assume your cluster was running a v2 of etcd before, things are likelier to come back online if you use that version. (It's the latest v2 released, v2.5.2 was a typo that should have been v2.2.5; this was fixed in master a few weeks ago).

**Comment by jalberto** [comment]
that worked! thanks!

I am trying to resume the upgrade now

**Comment by jackfrancis** [comment]
Thanks for being resilient here. You are contributing to acs-engine-driven upgrades becoming more of a 1st class feature, we appreciate it!

**Comment by jalberto** [comment]
@CecileRobertMichon I think this is not closed yet, I am still evaluating if everything is right after upgrade.

I can see problem mounting azure-disk volumes

**Comment by CecileRobertMichon** [comment]
@jalberto sorry about that, I thought the issue had been resolved. Re-opening it now.

**Comment by jalberto** [comment]
no prob @CecileRobertMichon 

So after upgrade my PVs using azure-file (shared volumes using CIFS) are not automatically created anymore (I have an storage class) even if created by hand, then it cannot be mounted becuase a permission problem.

More details in how StorageClass was created: https://github.com/Azure/acs-engine/issues/1506

**Comment by jalberto** [comment]
I fixed azurefile by deleting adn recreating the StorageClass

Now I got a new problem quite critical:

```
Multi-Attach error for volume "pvc-3a32c7b6-fd48-11e7-b811-000d3a2da567" Volume is already exclusively attached to one node and can't be attached to another 
```

This happens each time a pod need to move from one node to another. I checked in azure portal and I can see how the disk move to the correct node correctly, and kubectl says the PVC is bound.

probably related to: #2002

**Comment by andyzhangx** [comment]
@jalberto You got this error when moving pod with an azure disk (not azure file) to another node, right? This could happen since azure disk detach from a node costs minutes in current k8s version, but wait for a few  minutes should work.

**Comment by jalberto** [comment]
@andyzhangx even after 4h still not working

**Comment by andyzhangx** [comment]
@jalberto could you run "kubectl describe po POD-NAME" and paste the output here?

**Comment by andyzhangx** [comment]
@jalberto and what's your k8s version? is it managed disk VM or unmanaged disk VM? What's your k8s operations? `kubectl drain POD-NAME`? I would try to repro this issue in my env if possible.

**Comment by andyzhangx** [comment]
I have checked the k8s upstream code, it's likely due to incorrect status of volume status, that is the volume is actually removed from one node, while its volume status is not updated, volume still belonging to that node. I tried twice on my env, while It could not be easily reproed since it's due to Meltdown patch as you mentioned. So I would suggest you could follow this guide : [Volume status out of sync when kubelet restarts](https://github.com/kubernetes/kubernetes/issues/33203), one solution is restart kubelet in the original node and also the node with azure disk (`sudo systemctl restart kubelet`), and then after a few minutes, check the pod & volume status.

**Comment by jalberto** [comment]
thanks @andyzhangx for your time.
I only was able to "fix" it by rebooting whole node, this doesn't even count as a workaround, is someone in azure side fixing this?

This is critical, as if for whatever reason a pod is re-scheduler it will not get correct state

**Comment by andyzhangx** [comment]
@jalberto so your problem(`Multi-Attach error`) always happen in the rescheduler? could you also provide below info:
1. k8s version
2. your pod config

There is possiblity that in the `Intel CPU Azure update` around 2017.1.5, VM disk status is inconsistent, and workaround is as I suggested in https://github.com/Azure/acs-engine/issues/2002
```
az vm update -g <group> -n <name>
```

If that still does not work, run `sudo systemctl restart kubelet` in the two agent VMs.

**Comment by jalberto** [comment]
hi @andyzhangx I am on k8s 1.8.4 about pod configuratoin si nto important, as it happens with any pod using a disk.

I already tryed that workaround, but is temporal, it only fixes current inconsistencies, not future one, so each time a pod move to a different node it needs manual intervention to finish causing lot of problems.

**Comment by andyzhangx** [comment]
@jalberto Are you using deployment or statefulset? Per my experience, deployment with azure disk volumeMounts would have such issue, statefulset would ensure the disk has been removed before starting a new pod.

**Comment by malonedrakes19** [comment]
Im stuck at the setup  mode of my zte982. I can't get passed the email mode

**Comment by jalberto** [comment]
@andyzhangx 

```
❯ az vm update -g k8svl -n k8s-pool01-xxxxx-1
Cannot attach data disk 'k8svl-dynamic-pvc-xxxxxx' to VM 'k8s-pool01-xxxxx-1' because the disk is currently being detached or the last detach operation failed. Please wait until the disk is completely detached and then try again or delete/detach the disk explicitly again.
```

This happens _every_ time a pod with a persisten volumen needs to move

**Comment by jalberto** [comment]
This one is a Deployment (official traefik chart) but it happens the same with a StaefulSet @andyzhangx

**Comment by andyzhangx** [comment]
@jalberto would you try Powershell solution:
https://blogs.technet.microsoft.com/mckittrick/azure-vm-stuck-in-failed-state-arm/
```
Get-AzureRmVM -Name "VMname" -ResourceGroupName 'RGName' | Update-AzureRmVM 
```

**Comment by andyzhangx** [comment]
And what's your VM status now? This issue is related to VM status inconsistency, you may file an incident to Azure VM support.

**Comment by jalberto** [comment]
@andyzhangx check my comments in #2002 please

This is not a particular problem with my VMs (also created by acs-egine BTW) as I am no t the only one with this problem, also is not frist time as this seems a recurrent problem around here.

**Comment by andyzhangx** [comment]
@jalberto if you are using Deployment, you are very likely to hit this issue when reschedule a pod with azure disk mount on one VM to another. Would you try statefulset again this time?

**Comment by jalberto** [comment]
@andyzhangx I am using official helm chart, it's using a deployment, I knwo statefulset is better option, but root problem is not deployment vs statefulset is attach/dettach disk inconsistency in azure side.

I have exactly same problem with StatefulSet. To ask me to move a prod LB from official helm chart to custom StatefulSet cannot be a solution for this, not even temporal one.

This happens every tie, any o my pods need to move, mostly of my pods with volumes are StatefuSet. The problem is not there, but in Azure

**Comment by andyzhangx** [comment]
One workaround is let that helm chart use azure file, you may change the default storage class as azurefile if your helm chart is using `default` storage class. Move pod with azure disk mount from one node to another node is really not a good solution since attach/detach disk from a VM sometimes costs minutes. Azure file won't have such attach/detach issue.

**Comment by andyzhangx** [comment]
@jalberto BTW, what's your helm chart and other config? I may try to repro on my testing env if possible. Thanks.

**Comment by jalberto** [comment]
@andyzhangx thanks for your time.

- chart is using azure disk, to move to azure file meant to lost current data
- this is the chart (but it happens with other charts): https://github.com/kubernetes/charts/tree/master/stable/traefik

**Comment by andyzhangx** [comment]
@jalberto Hi, I have tried on my testing env using deployment with azure disk mount, when scheduling a pod from one node to another, there will be around 3mins hitting following error:
```
Multi-Attach error for volume "pvc-c048abf5-1189-11e8-846f-000d3af71b87" Volume is already exclusively attached to one node and can't be attached to another
```
But after 3mins, it will recover and shows mounting successfully on another node.

So for your issue, there is a possible solution to mitigate, that is 
1. create new nodes by [acs-engine scale up](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/scale.md)
2. kubectl drain old nodes which was created before 2017.1.5 that have this attach error issue
3. delete your old VMs

**Comment by jalberto** [comment]
closing even if this is not solve in anyway, but there is a follow up in #2567

**Comment by andyzhangx** [comment]
The disk attach error is probably due to lack of lock before detach disk, below are all details, I would encourage to use fixed version:

### 1. disk attach error
**Issue details**:

In some corner case(detaching multiple disks on a node simultaneously), when scheduling a pod with azure disk mount from one node to another, there could be lots of disk attach error(no recovery) due to the disk not being released in time from the previous node. This issue is due to lack of lock before DetachDisk operation, actually there should be a central lock for both AttachDisk and DetachDisk opertions, only one AttachDisk or DetachDisk operation is allowed at one time.

The disk attach error could be like following:
```
Cannot attach data disk 'cdb-dynamic-pvc-92972088-11b9-11e8-888f-000d3a018174' to VM 'kn-edge-0' because the disk is currently being detached or the last detach operation failed. Please wait until the disk is completely detached and then try again or delete/detach the disk explicitly again.
```

**Related issues**
 - [Azure Disk Detach are not working with multiple disk detach on the same Node](https://github.com/kubernetes/kubernetes/issues/60101)
 - [Since Intel CPU Azure update, new Azure Disks are not mounting, very critical... ](https://github.com/Azure/acs-engine/issues/2002)
 - [Busy azure-disk regularly fail to mount causing K8S Pod deployments to halt](https://github.com/Azure/ACS/issues/12)

**Mitigation**:
 - option#1: Update every agent node that has attached or detached the disk in problem
 
###### in Azure cloud shell, run
```
$vm = Get-AzureRMVM -ResourceGroupName $rg -Name $vmname  
Update-AzureRmVM -ResourceGroupName $rg -VM $vm -verbose -debug
```
###### in Azure cli, run
```
az vm update -g <group> -n <name>
```

 - option#2: 
1) ```kubectl cordon node``` #make sure no scheduling on this node
2) ```kubectl drain node```  #schedule pod in current node to other node
3) restart the Azure VM for node via the API or portal, wait untli VM is "Running"
4) ```kubectl uncordon node```
 
**Fix**
 - PR [fix race condition issue when detaching azure disk](https://github.com/kubernetes/kubernetes/pull/60183) has fixed this issue by add a lock before DetachDisk

| k8s version | fixed version |
| ---- | ---- |
| v1.6 | no fix since v1.6 does not accept any cherry-pick |
| v1.7 | 1.7.14 |
| v1.8 | 1.8.9 |
| v1.9 | 1.9.5 |
| v1.10 | 1.10.0 |

**Comment by jalberto** [comment]
thanks @andyzhangx but this problem continue happening in 1.9.6 deployed with 0.14.5, a simple upgrade can take up to 1h to be complete

**Comment by andyzhangx** [comment]
@jalberto is it still disk attach error or some other error?

**Comment by andyzhangx** [comment]
@jalberto 
The new cluster means v1.9.6? Could you paste that error msg again? 
And do you have a clean config to repro this issue, I would like to repro it in my env if it's after v1.9.5.

**Comment by jalberto** [comment]
yes 1.9.6 deployed with acs 0.14.5

you can check my apimodel in #2567 

I cannot paste it now, but the error is the typical "Multi attach error"

**Comment by jalberto** [comment]
@andyzhangx , this is the error:

```
 Multi-Attach error for volume "pvc-3ca68971-35d7-11e8-a4e3-000d3a205895" Volume is already exclusively attached to one node and can't be attached to another
Unable to mount volumes for pod "vpn-openvpn-69bc585689-fz77t_default(d4a11d6b-3978-11e8-aa0a-000d3a205895)": timeout expired waiting for volumes to attach/mount for pod "default"/"vpn-openvpn-69bc585689-fz77t". list of unattached/unmounted volumes=[certs] 
```

32mins and counting :)

**Comment by andyzhangx** [comment]
Hi @jalberto, so azure disk has been moved to the right node? `Multi-Attach error for volume` msg is from kubelet on those two nodes, a quick workaround is run `sudo systemctl restart kubelet` on the two nodes.

**Comment by jalberto** [comment]
@andyzhangx yes, usually a combination of `kubelet restart` and `az vm update` works, but to reuire manual intervention each time a pod moves is clearly a signal something is wrong

**Comment by andyzhangx** [comment]
@jalberto  when scheduling from one node to another, how many disks were attached in one node? I would like to repro this in my env, and you were using `deployment`, right?

**Comment by jalberto** [comment]
this cluster has only 2 PVs so from 0 to 2

**Comment by andyzhangx** [comment]
Hi @jalberto, I tried to repro it on my testing env(v1.9.6), while after around 9min, all 3 pods were scheduled from node#1 to node#2 successfully, here are the detailed steps: https://github.com/andyzhangx/demo/tree/master/linux/azuredisk/attach-stress-test/deployment

I would like to make sure:
1. You controller manager on master is v1.9.6, could you paste:
```
sudo cat /etc/kubernetes/manifests/kube-controller-manager.yaml | grep image
image: "k8s-gcrio.azureedge.net/hyperkube-amd64:v1.9.6"
```

2. You controller manager on master never dies in the pod rescheduling process, if it dies, the reschedule will never succeed, could you paste:
```
docker ps | grep hyperkube
```

**Comment by jalberto** [comment]
thanks @andyzhangx, here you go:

1. `image: "k8s-gcrio.azureedge.net/hyperkube-amd64:v1.9.6"`
2.
```
b8ca93010771        k8s-gcrio.azureedge.net/hyperkube-amd64            "/hyperkube contro..."   32 hours ago        Up 32 hours                             k8s_kube-controller-manager_kube-controller-manager-k8s-master-22440456-1_kube-system_095c64aa225fa3433b371fd804b5f98f_4
f72d9cb83a0d        k8s-gcrio.azureedge.net/hyperkube-amd64            "/hyperkube proxy ..."   3 days ago          Up 3 days                               k8s_kube-proxy_kube-proxy-m92p8_kube-system_01a9e261-3480-11e8-a4e3-000d3a205895_2
a702569da1d4        k8s-gcrio.azureedge.net/hyperkube-amd64            "/hyperkube schedu..."   3 days ago          Up 3 days                               k8s_kube-scheduler_kube-scheduler-k8s-master-22440456-1_kube-system_5429d7b62d0f50e1c40f54b7f3d7b13f_2
4ffac9c55c50        k8s-gcrio.azureedge.net/hyperkube-amd64            "/hyperkube apiser..."   3 days ago          Up 3 days                               k8s_kube-apiserver_kube-apiserver-k8s-master-22440456-1_kube-system_3e253a421bdf6519a931b2e1c19a4cef_5
ddbe4816f57b        k8s-gcrio.azureedge.net/hyperkube-amd64:v1.9.6     "/hyperkube kubele..."   3 days ago          Up 3 days                               priceless_cori
```

Notice my problems in 1.9.6 are random in both, time lasting and occurence. Still 9mins seems excessive for a mount/umount operation

**Comment by andyzhangx** [comment]
@jalberto thanks for the info, finally I reproed this issue by using StatefulSet, [detailed steps with statefulset](https://github.com/andyzhangx/demo/tree/master/linux/azuredisk/attach-stress-test/statefulset)
The root cause is `node.volumesInUse` is incorrect in my repro, it could be a common k8s issue:
https://github.com/kubernetes/kubernetes/issues/62282

To validate my finding, could you help run `kubectl get no -o yaml` and paste the `node.volumesInUse` & `node.volumesAttached` values of the two nodes? As I could find up to now, restart kubelet manually in both nodes would work.

**Comment by jalberto** [comment]
@andyzhangx 

```
    volumesAttached:
    - devicePath: "0"
      name: kubernetes.io/azure-disk//subscriptions/3dd693dd-25f9-471b-a404-19e064398e85/resourceGroups/vlacs01/providers/Microsoft.Compute/disks/vlacs01-5abedde3-dynamic-pvc-c621a5ed-3483-11e8-a344-000d3a205d6f
    volumesInUse:
    - kubernetes.io/azure-disk//subscriptions/3dd693dd-25f9-471b-a404-19e064398e85/resourceGroups/vlacs01/providers/Microsoft.Compute/disks/vlacs01-5abedde3-dynamic-pvc-c621a5ed-3483-11e8-a344-000d3a205d6f
    - kubernetes.io/azure-disk/m3606615189

    volumesAttached:
    - devicePath: "1"
      name: kubernetes.io/azure-disk//subscriptions/3dd693dd-25f9-471b-a404-19e064398e85/resourceGroups/vlacs01/providers/Microsoft.Compute/disks/vlacs01-5abedde3-dynamic-pvc-3ca68971-35d7-11e8-a4e3-000d3a205895
    volumesInUse:
    - kubernetes.io/azure-disk//subscriptions/3dd693dd-25f9-471b-a404-19e064398e85/resourceGroups/vlacs01/providers/Microsoft.Compute/disks/vlacs01-5abedde3-dynamic-pvc-3ca68971-35d7-11e8-a4e3-000d3a205895
    - kubernetes.io/azure-disk/m2462769329
```

Which is the time goal for this task? probably should be in the seconds order not minutes?

**Comment by andyzhangx** [comment]
@jalberto from your `node.volumesAttached` and `node.volumesInUse` the status of both two nodes is recovered. The detach or attach disk could cost around 1 min, so for two disks, rescheduling from one node to another should cost about 4 min. The long time waiting could be due to `node.volumesInUse` not updated correctly in kubelet.

**Comment by jalberto** [comment]
@andyzhangx  this happens too in AKS vanilla cluster 1.9.6 (just deployed)

![screenshot from 2018-04-11 12-54-22](https://user-images.githubusercontent.com/99927/38612638-a6bc201e-3d87-11e8-876a-bc09e2d43ee1.png)

**Comment by andyzhangx** [comment]
@jalberto is that volume removed in the node while still in that node's `volumesInUse` list?

**Comment by andyzhangx** [comment]
@jalberto pls also paste the `volumesAttached`, `volumesInUse` on the two nodes, I am collecting such info. This could be a k8s common issue. Thanks.

**Comment by jalberto** [comment]
@andyzhangx 2 hours already :)

![screenshot from 2018-04-11 15-39-36](https://user-images.githubusercontent.com/99927/38620373-9b32cec0-3d9e-11e8-8426-a2b3cbe01a87.png)

```
    volumesAttached:
    - devicePath: "0"
      name: kubernetes.io/azure-disk//subscriptions/3dd693dd-25f9-471b-a404-19e064398e85/resourceGroups/MC_aksprod-1_aksprod-1_westeurope/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-aa77e11d-3ccc-11e8-94ea-0a58ac1f1128
    volumesInUse:
    - kubernetes.io/azure-disk//subscriptions/3dd693dd-25f9-471b-a404-19e064398e85/resourceGroups/MC_aksprod-1_aksprod-1_westeurope/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-aa77e11d-3ccc-11e8-94ea-0a58ac1f1128
    - kubernetes.io/azure-disk//subscriptions/3dd693dd-25f9-471b-a404-19e064398e85/resourceGroups/MC_aksprod-1_aksprod-1_westeurope/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-ffa219b5-3d74-11e8-94ea-0a58ac1f1128
    - kubernetes.io/azure-disk/m3576630252
```

```
    volumesAttached:
    - devicePath: "2"
      name: kubernetes.io/azure-disk//subscriptions/3dd693dd-25f9-471b-a404-19e064398e85/resourceGroups/MC_aksprod-1_aksprod-1_westeurope/providers/Microsoft.Compute/disks/kubernetes-dynamic
-pvc-ffa219b5-3d74-11e8-94ea-0a58ac1f1128
    - devicePath: "0"
      name: kubernetes.io/azure-disk//subscriptions/3dd693dd-25f9-471b-a404-19e064398e85/resourceGroups/MC_aksprod-1_aksprod-1_westeurope/providers/Microsoft.Compute/disks/kubernetes-dynamic
-pvc-5e02b94c-3d6a-11e8-94ea-0a58ac1f1128
    volumesInUse:
    - kubernetes.io/azure-disk//subscriptions/3dd693dd-25f9-471b-a404-19e064398e85/resourceGroups/MC_aksprod-1_aksprod-1_westeurope/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-06d1f6b9-3d70-11e8-94ea-0a58ac1f1128
    - kubernetes.io/azure-disk//subscriptions/3dd693dd-25f9-471b-a404-19e064398e85/resourceGroups/MC_aksprod-1_aksprod-1_westeurope/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-5e02b94c-3d6a-11e8-94ea-0a58ac1f1128
    - kubernetes.io/azure-disk//subscriptions/3dd693dd-25f9-471b-a404-19e064398e85/resourceGroups/MC_aksprod-1_aksprod-1_westeurope/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-ffa219b5-3d74-11e8-94ea-0a58ac1f1128
    - kubernetes.io/azure-disk/m2688977947
    - kubernetes.io/azure-disk/m3600819570
    - kubernetes.io/azure-disk/m570158133
```
