### ISSUE TITLE
Kubernetes cluster deployment ends in error state with prometheus-grafana

### ISSUE THREAD

**Issue by starkilla2003** [Azure/acs-engine#2142]
**Is this a request for help?**:

YES

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

0.12.4

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes v1.7.9

**What happened**:
I deployed a Kubernetes Cluster from scratch into the Azure Germany environment with the prometheus-grafana extension. The cluster was deployed via the following JSON-File:

`{
  "apiVersion": "vlabs",
  "location": "germanycentral",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "yestest",
      "vmSize": "Standard_D2_v2",
	  "storageProfile": "ManagedDisks"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet",
		 "storageProfile": "ManagedDisks",
		 "extensions": [
          { 
            "name": "prometheus-grafana-k8s"
          }
		  ]
      }
    ],
    "linuxProfile": {
      "adminUsername": "",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "extensionProfiles": [
      { 
        "name": "prometheus-grafana-k8s", 
        "version": "v1",
        "rootURL": "https://raw.githubusercontent.com/Azure/acs-engine/master/"
      }
    ],
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
`
After the deployment the monitoring-prometheus-server ends up in an error state with the following error:

`PersistentVolumeClaim is not bound: "monitoring-prometheus-server" (repeated 3 times)
Unable to mount volumes for pod "monitoring-prometheus-server-4039493558-bcgdq_default(68f458f4-0108-11e8-800e-0017fa1052b9)": timeout expired waiting for volumes to attach/mount for pod "default"/"monitoring-prometheus-server-4039493558-bcgdq". list of unattached/unmounted volumes=[storage-volume]
Error syncing pod`

**What you expected to happen**:
Running cluster with a working prometheus and grafana combination.

**How to reproduce it** (as minimally and precisely as possible):
As I wrote I just deployed a cluster into the Azure Germany cloud with the conifgration as above.

**Anything else we need to know**:

**Comment by dtzar** [comment]
With the 5.x version of the chart being released Jan 23, there is no way this extension will work because prometheus was updated to 2.x and the values file is significantly different (i.e. the configmap values inside the chart).  I don't think this is related to the error you're experiencing... nonetheless I am looking to make this work now.  Tagging these folks for visibility @ritazh @trstringer

**Comment by starkilla2003** [comment]
Thank you for reply and i am looking forward to the changes. We want to use this option in a customer scenario so this topic is a bit time critical.

**Comment by trstringer** [comment]
@starkilla2003 while troubleshooting this issue, it brought me to another problem that I'm currently working through. When that one is resolved (hopefully soon) I should be able to circle back to this specific error.

I just wanted to let you know somebody is working on it!

**Comment by dtzar** [comment]
I ran into [this issue](https://github.com/kubernetes/charts/issues/3491) while trying to get the 5.x version of the helm chart to deploy and got stuck there.  I believe if we deploy a fresh 1.9 K8s cluster with RBAC enabled we will hit this same problem since these are the default admission controller values, but haven't had a chance to try yet.

@trstringer - your error might be due to these changes in the values.yaml file:
```
serverFiles:
 -  alerts: ""
 -  rules: ""
 +  alerts: {}
 +  rules: {}
  
 -  prometheus.yml: |-
 +  prometheus.yml:
      rule_files:
``` 
In the PR to update to 2.x https://github.com/kubernetes/charts/pull/2767/files

**Comment by ritazh** [comment]
@dtzar I think that PR is making that chart no longer backward compatible with older version of  prometheus. The parameters should be updated conditionally based on prometheus version.

**Comment by starkilla2003** [comment]
Hello, with acs-engine v0.13.0 the prometheus grafana deployment is working. But i don't get any metrics in the default dashboard. Should i open a seperate issue for that?

**Comment by trstringer** [comment]
@starkilla2003 there is actually an open PR right now https://github.com/Azure/acs-engine/pull/2274 to switch out the dashboard with a better one that has more support for Prometheus v2 output. Once this gets merged in, you should have a better solution.

**Comment by starkilla2003** [comment]
@trstringer I saw that PR and deployed the mentioned dashboard, but even with that it is not working.

**Comment by trstringer** [comment]
@starkilla2003 what are you seeing in the dashboard? No metrics coming through (all saying "N/A")?

**Comment by starkilla2003** [comment]
@trstringer Do you by chance have an idea what the problem could be? As you said there are no metrics coming through at the moment. We are trying to fix that situation at the moment, but seem to get nowhere.

**Comment by starkilla2003** [comment]
Findings so far:

- Prometheus needs a service account, because it has no access to node level scraping
- cadvisor is not running, so all container metrics are not available

Is there any reason that cadvisor is disabled in acs-engine?

**Comment by trstringer** [comment]
@starkilla2003 can you please run `kubectl get po` (or `kubectl get po -n <monitoring_namespace>` if you installed the extension in a non-default namespace) and paste the output here?

**Comment by starkilla2003** [comment]
`NAME                                                        READY     STATUS    RESTARTS   AGE
dashboard-grafana-75b87dc654-ltcrb                          1/1       Running   0          4d
monitoring-prometheus-kube-state-metrics-6b7bc5b446-7bpxl   1/1       Running   0          4d
monitoring-prometheus-node-exporter-nprbc                   1/1       Running   0          4d
monitoring-prometheus-node-exporter-xd2j4                   1/1       Running   0          4d
monitoring-prometheus-node-exporter-zqf2g                   1/1       Running   0          4d
monitoring-prometheus-pushgateway-c896596b4-m7cfx           1/1       Running   0          4d
monitoring-prometheus-server-7ddf9c5d55-kkc9d               2/2       Running   0          58m`

**Comment by trstringer** [comment]
Do you still have the `acs-engine deploy` command that you used to deploy this cluster/extension? I'll see if I can repro.

**Comment by starkilla2003** [comment]
I generated the cluster with the following config:

{
  "apiVersion": "vlabs",
  "location": "germanycentral",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
	  "orchestratorVersion": "1.8.8",
      "kubernetesConfig": {
        "networkPolicy": "calico",
        "maxPods": 16,
        "gcHighThreshold": 70,
        "gcLowThreshold": 40
      }
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "production",
      "vmSize": "Standard_D2_v2",
      "storageProfile": "ManagedDisks"
    },
    "agentPoolProfiles": [
      {
        "name": "testnodes",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "storageProfile": "ManagedDisks",
        "availabilityProfile": "AvailabilitySet",
		"extensions": [
          { 
            "name": "prometheus-grafana-k8s"
          }
		]
      }
    ],
    "linuxProfile": {
      "adminUsername": "testadmin",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
	"extensionProfiles": [
      { 
        "name": "prometheus-grafana-k8s", 
        "version": "v1",
        "rootURL": "https://raw.githubusercontent.com/Azure/acs-engine/master/"
      }
    ],
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}

That was the state after deploying with the generated json files. I deployed via az group deployment create in AzureGermanCloud.

Please let me know if you need additional information. Thank you for the help and time!

**Comment by trstringer** [comment]
```
"rootURL": "https://raw.githubusercontent.com/Azure/acs-engine/master/"
```

The new dashboard isn't in `Azure/acs-engine/tree/master` yet. This is the PR that is pending merge: https://github.com/Azure/acs-engine/pull/2274

[This is the dashboard](https://grafana.com/dashboards/3119/revisions) that should work (and the PR is basically just that). Try installing that dashboard manually so we could rule that out.

**Comment by starkilla2003** [comment]
@trstringer I already imported that dashboard and I am using the dashboard with the id 3119.

**Comment by trstringer** [comment]
Can you check and verify the data source is linked up? At this point it might be wise to pop open Prometheus and use that UI to see if there's any data in Prometheus. It's hard to tell right now if the problem is Prometheus not getting data, or Grafana not getting data from Prometheus.

**Comment by trstringer** [comment]
1. Connect to the Prometheus instance: `kubectl port-forward <prometheus_server_pod> 9090:9090`
1. Open your browser and navigate to `localhost:9090`
1. In the query explorer type: `node_cpu`
1. View the output

Is there data there?

**Comment by starkilla2003** [comment]
Ok, the metric `node_cpu` came up when we added the serviceaccountname for prometheus_server_pod. That one was missing before that. But all the metrics like `container_cpu_usage_seconds_total` are missing in the prometheus server and are referenced in the dashboard.

**Comment by trstringer** [comment]
1. Run `kubectl get no`
1. ssh into a master node
1. From the master node `curl <agent_node_hostname>:4194/metrics | grep container_cpu`

Does that succeed? And do you get data back?

**Comment by starkilla2003** [comment]
I get a connection refused when i try to curl from a master node to an agent node on that port.

**Comment by starkilla2003** [comment]
Tell me if i am wrong, but for the c`ontainer_cpu_usage_seconds_total `we would need a `cadvisor` running. But after deploying with acs-engine cadvisor is disabled.

**Comment by starkilla2003** [comment]
As far as i can see in the kubelet cAdvisor has the port 0 which means it is disabled in this case.

When trying to curl on an agent node I also get a connection refused.

**Comment by trstringer** [comment]
So is cAdvisor running elsewhere in your cluster? If so, the Prometheus config would have to be updated to reflect that. As of now the job that scrapes this data is as follows:

```
- bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token                                                                                       
  job_name: kubernetes-nodes-cadvisor                                                                                                                          
  kubernetes_sd_configs:                                                                                                                                       
  - role: node                                                                                                                                                 
  relabel_configs:                                                                                                                                             
  - action: labelmap                                                                                                                                           
    regex: __meta_kubernetes_node_label_(.+)                                                                                                                   
  - replacement: kubernetes.default.svc:443                                                                                                                    
    target_label: __address__                                                                                                                                  
  - regex: (.+)                                                                                                                                                
    replacement: /api/v1/nodes/${1}:4194/proxy/metrics                                                                                                         
    source_labels:                                                                                                                                             
    - __meta_kubernetes_node_name                                                                                                                              
    target_label: __metrics_path__                                                                                                                             
  scheme: https                                                                                                                                                
  tls_config:                                                                                                                                                  
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt                                                                                              
    insecure_skip_verify: true 
```

Did you specifically disable cAdvisor from the kubelet? Or was that just how your cluster was deployed? If the former, was there a reason behind that?
