### ISSUE TITLE
No examples of using an existing Managed Disk with a Persistent Volume Claim

### ISSUE THREAD

**Issue by anschoewe** [Azure/acs-engine#2299]
**Is this a request for help?**:
---
Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
Feature Request

**What version of acs-engine?**:
---
I'm using the AKS preview in Azure.  I'm not sure which acs-engine that corresponds to.

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.8.1

**What happened**:
Trying to use an existing Managed Disk, that is pre-filled with data, as a persistent volume (PV) will fulfill a persistent volume claim (PVC) found in the Kubernetes application yaml files.   The PV is successfully created. The PVC does successfully bind to the PV.  But when my application starts and attempt to use the PVC, I see the following error:

> AttachVolume.Attach failed for volume "jenkins-home" : Attach volume "jenkins-home" to instance "aks-agentpool-40897452-0" failed with compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="OperationNotAllowed" Message="Addition of a blob based disk to VM with managed disks is not supported."

**What you expected to happen**:
I expected the existing Managed Disk would be used when attached to the agent node.  Instead it see's the underlying VHD used to produce the Managed Disk and complains that you can't mount a blob to a VM.  Instead, I need a way to point the Persistent Volume to a Managed Disk and NOT a VHD.

**How to reproduce it** (as minimally and precisely as possible):
My setup to reproduce it can be found in [this Stackoverflow question](https://stackoverflow.com/questions/48774021/how-to-configure-a-manually-provisioned-azure-managed-disk-to-use-as-a-kubernete)

**Anything else we need to know**:
I'm hoping this is possible and I'm just not doing it correctly.  An example solution to this use case would be helpful.

**Comment by andyzhangx** [comment]
@anschoewe Here is the [example](https://github.com/andyzhangx/Demo/tree/master/linux/azuredisk#static-provisioning-for-azure-disk), pls note that managed disk could only be attached to VM with managed os disk, blob based disk could only be attached to VM with blob based os disk.

**Comment by anschoewe** [comment]
Thanks @andyzhangx .  [This is very helpful](https://raw.githubusercontent.com/andyzhangx/Demo/master/linux/azuredisk/nginx-pod-azuredisk-static-mgrdisk.yaml).  I had tried to use the managed disk resource ID before but it yelled at me saying it expected a .vhd file.  But after adding 'kind: Managed', it was perfectly happy to take the managed disk resource id.  It was also very important to move/copy the managed disk into the same resource group as my AKS/Kubernetes cluster before creating/applying this PV and PVC definitions.

So now my PV and PVC look like this and it's working...

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-home
spec:
  capacity:
    storage: 10Gi
  storageClassName: default
  azureDisk:
    kind: Managed
    diskName: jenkins-home
    diskURI: /subscriptions/{subscription-id}/resourceGroups/{aks-controlled-resource-group-name}/providers/Microsoft.Compute/disks/jenkins-home
    fsType: ext4
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: jenkins-home-pvc
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default
```

This resolve my issue.
