### ISSUE TITLE
GID & mount-options annotations not working

### ISSUE THREAD

**Issue by jalberto** [Azure/acs-engine#2307]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.11.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
GID & mount-options annotations seems to be ignored by azure 

**What you expected to happen**:
By using any combination of this annotations I expect the volume to be mounted following defiend options, instead the volume is mounted as root

After mounted I am able to do `chown -R N:N /mountPoint`

Example:

```
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        {{- if .Values.common.stateful.gid }}
        pv.beta.kubernetes.io/gid: {{ .Values.common.stateful.gid | quote }}
        volume.beta.kubernetes.io/mount-options: "uid={{ .Values.common.stateful.gid }},gid={{ .Values.common.stateful.gid }}"
        {{- end }}
        volume.beta.kubernetes.io/storage-class: {{ .Values.common.stateful.class }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.data.stateful.size }}
  {{- end }}
```

**How to reproduce it** (as minimally and precisely as possible):

Use VolumeClaimTemplate pasted in previous step in StatefulSet:

```
apiVersion: apps/v1beta2
kind: StatefulSet
```

**Anything else we need to know**:
