### ISSUE TITLE
Can't deploy Windows Container to Hybrid Cluster with "none" network policy

### ISSUE THREAD

**Issue by idanshahar** [Azure/acs-engine#2343]
**Is this a request for help?**:

YES

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

v0.13.0, v0.12.5, v0.11.0 (all of them)

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
After deploying a hybrid cluster, I tried to deploy IIS pod.
The container stuck on ContainerCreating status.
```
Events:
  Type     Reason                 Age                 From                   Message
  ----     ------                 ----                ----                   -------
  Normal   Scheduled              10m                 default-scheduler      Successfully assigned node-example-75d8ff6f7c-dq728 to 35352k8s9010
  Normal   SuccessfulMountVolume  10m                 kubelet, 35352k8s9010  MountVolume.SetUp succeeded for volume "default-token-q788v"
  Normal   SandboxChanged         9m (x8 over 10m)    kubelet, 35352k8s9010  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedSync             12s (x98 over 10m)  kubelet, 35352k8s9010  Error syncing pod
```

The Windows Agents version is 1709 RS3

docker images command on the Windows Agents shows that the IIS Docker Image isn't even pulled.

 **kubletwin/pause container on the Windows agent is always restarting.**

**How to reproduce it** (as minimally and precisely as possible):
1. Create a cluster from the template:
[kubernetes-windows-template.json.txt](https://github.com/Azure/acs-engine/files/1760886/kubernetes-windows-template.json.txt)

2. Deploy the following IIS deployment yaml:
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: iis
  labels:
    app: iis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iis
  template:
    metadata:
      labels:
        app: iis
    spec:
      nodeSelector:
        beta.kubernetes.io/os: windows
      containers:
      - name: iis
        image: microsoft/iis:1709
        ports:
        - containerPort: 80
```
