### ISSUE TITLE
Hybrid cluster external IP does not route to service

### ISSUE THREAD

**Issue by jsturtevant** [Azure/acs-engine#2361]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
ISSUE

**What version of acs-engine?**:
---
Version: v0.12.4                                                                             
GitCommit: 069d9e4                                                                         
GitTreeState: clean 

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
kuberentes 1.9.1

**What happened**:
Created a hybrid cluster with 1 master, 1 linux node, 2 windows nodes.  Deployed a nginx to the linux node and created a LB service.  Went to the IP address of service and there is no service available.

**What you expected to happen**:
When I go to the IP address for the service I would expect to see nginx default page.  This work previously in december.

**How to reproduce it** (as minimally and precisely as possible):
Use the template:

```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.9"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "acsengine-hybrid",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "windowspool2",
        "count": 2,
        "vmSize": "Standard_D2_v3",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Windows"
      },
      { 
        "name": "linuxpool2",
        "count": 1,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Linux"
      }
    ],
    "windowsProfile": {
      "adminUsername": "azureuser",
      "adminPassword": ""
    },
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
```

Then deploy the following service with `kubectl apply -f nginx-service.yaml`

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: echoserver
        image: nginx
        ports:
        - containerPort: 80
      nodeSelector: 
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: nginx
  type: LoadBalancer
```

run `kubectl get svc nginx` and navigate to ip address given.

**Anything else we need to know**:
The Azure Load Balancer and rule that was created when the kuberentes LB service points to the windows avalibility set and not to the linux node:

![image](https://user-images.githubusercontent.com/648372/36810383-619df40e-1c7f-11e8-9739-bb7f76a82e94.png)

I am able to work around it by adding an annotation to the service point to the specific linux availability set:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx
   annotations:
     service.beta.kubernetes.io/azure-load-balancer-mode: linuxpool2-availabilitySet-33087051
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: nginx
  type: LoadBalancer
```

I also found that if I upgraded to version 0.13 of acs-engine works with out the above work around.
