### ISSUE TITLE
No unmanaged Azure storage classes

### ISSUE THREAD

**Issue by j03wang** [Azure/acs-engine#2507]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: 0.14.2 (and probably versions prior)

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.9.5

**What happened**:
[Unmanaged Azure storage classes](https://github.com/Azure/acs-engine/blob/master/parts/k8s/addons/kubernetesmasteraddons-unmanaged-azure-storage-classes.yaml) look like they're a copy-paste of the managed storage classes.

**What you expected to happen**:
unmanaged-standard and unmanaged-premium to be provisioned when creating the cluster.

**How to reproduce it** (as minimally and precisely as possible):
Deploy the cluster.

**Anything else we need to know**:

**Comment by andyzhangx** [comment]
@j03wang if `kind` field is not specified, it's unmanaged azure disk storage class, also called blob based disk
```
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/azure-disk
parameters:
  cachingmode: None
```
