### ISSUE TITLE
Error deploying < 4 Windows nodes fails - sometimes

### ISSUE THREAD

**Issue by BIGPHATTOBY** [Azure/acs-engine#2511]
**Is this a request for help?**:
Yes please.
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
v0.14.4
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes, 1.9.1 - 6

**What happened**:
When trying to create a deployment with 8 windows nodes a linux node (hybrid cluster) it fails.
Same config but with 4 window nodes gets deployed just fine, 4 seems to be the limit.

The errors received is:
 ```json
{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'cse0'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=3\n[stdout]\n\n[stderr]\n\"."
      }
    ]
  }
}
```
```json
"submissionTimestamp": "2018-03-22T13:39:43.1614128Z",
    "subscriptionId": "xxxxxxx",
    "properties": {
        "statusCode": "Conflict",
        "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceDeploymentFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"VMExtensionProvisioningError\",\"message\":\"VM has reported a failure when processing extension 'cse0'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=3\\n[stdout]\\n\\n[stderr]\\n\\\".\"}]}}"
```

**What you expected to happen**:
Well, to deploy.
I have done around 10 deployments of a 8 windows node, 1 linux node hybrid, out of these 9 deployments, only 1 was successful. 

**How to reproduce it** (as minimally and precisely as possible):
```bash
acs-engine generate --api-model acs-engine-deployment.json
```
```yaml
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.9.3"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "econo-prod-k8s-test-one",
      "vmSize": "Standard_D2_v3"
    },
    "agentPoolProfiles": [
      {
        "name": "alwayson",
        "count": 4,
        "vmSize": "Standard_D2_v3",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Windows"
      },
      {
        "name": "ondemand",
        "count": 4,
        "vmSize": "Standard_D2_v3",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Windows"
      },
      {
        "name": "proxy",
        "count": 1,
        "vmSize": "Standard_D2_v3",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Linux"
      }
    ],
    "windowsProfile": {
      "adminUsername": "",
      "adminPassword": ""
    },
    "linuxProfile": {
      "adminUsername": "",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
```
```bash
acs-engine deploy --subscription-id xxx-xxx-xx-xxxx \
    --dns-prefix your-dns-prefix --location westeurope \
    --auto-suffix --api-model acs-engine-deployment.json
```

**Anything else we need to know**:
This is working when trying to deploy fewer nodes.
