### ISSUE TITLE
ACS Engine Kubernetes AAD integration - fails to login

### ISSUE THREAD

**Issue by ionutgrecu-adv365** [Azure/acs-engine#2556]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
v0.14.4
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes v1.8.10

**What happened**:
I tried to integrate AAD with an ACS-Engine Kubernetes cluster.

**What you expected to happen**:
Authenticate to my Kubernetes cluster using the token issued by AAD. 

**How to reproduce it** (as minimally and precisely as possible):
1. I've deployed the Kubenetes cluster using acs-engine
 `acs-engine deploy --subscription-id <subscription_id> --resource-group <resource_group_name> --location <location> --auto-suffix --api-model .\kubernetes.json`
2. Created 2 applications in AAD following [Microsoft Azure Container Service Engine - Kubernetes AAD integration Walkthrough](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/aad.md)
3. Added the following arguments to the kube-apiserver.yaml manifest on the master:
`--oidc-client-id=spn:<APPID>
--oidc-issuer-url=https://sts.windows.net/<tenant_id>/
--oidc-username-claim=email`
4. Restarted the kubelet service on the master
5. Created a cluster role binding 
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: myuser-view
subjects:
  - kind: User
    name: '<my_email_address>'
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
```
6. Added a new user to kubeconf file
```
- name: bob
  user:
    auth-provider:
      config:
        apiserver-id: <api_server_id>
        client-id: <client_id>
        tenant-id: <tenant_id>
      name: azure
```
When I run `kubectl` for the first time I'm prompted to sign in and I'm getting the following message:

```
kubectl get pods
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <code> to authenticate.
error: You must be logged in to the server (Unauthorized)
```

Here is the api server log from /var/log/containers/kube-apiserver-k8s-master...fdadw4.log

`{"log":"E0329 11:06:29.522571       1 authentication.go:64] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, crypto/rsa: verification error]]\n","stream":"stderr","time":"2018-03-29T11:06:29.523195906Z"}`
 
I've checked JWT claims from the received token and are correct:
```
"aud": "spn:<api_server_id",
"iss": "https://sts.windows.net/<tenant_id/",
"email": "<my_email_address>",

```

**Anything else we need to know**:
