### ISSUE TITLE
AzureFile Mount fails - putting new line between storage account and domain

### ISSUE THREAD

**Issue by BrendanThompson** [Azure/acs-engine#2818]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
`v0.16.0`
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9

**What happened**:

When trying to use an Azure File Mount like below, it fails to mount.

```yaml
        volumeMounts:
        - name: asa-otm
          mountPath: /opt/my-app/otm
      volumes:
      - name: asa-otm
        azureFile:
          secretName: asa-otm
          shareName: otm
          readOnly: false
```

**What you expected to happen**:
One expects the account to mount

**Anything else we need to know**:

The following is the output from the pod:

```
Warning  FailedMount            11s                kubelet, k8s-agentpool0-18189144-2  MountVolume.SetUp failed for volume "asa-otm" : mount failed: exit status 1
Mounting command: mount
Mounting arguments: -t cifs -o username=saausnprddevotm
,password=PASSWORD
,file_mode=0755,dir_mode=0755,vers=3.0 //saausnprddevotm
.file.core.windows.net/otm /var/lib/kubelet/pods/3ae17688-4cdd-11e8-9240-000d3ae0c5ae/volumes/kubernetes.io~azure-file/asa-otm
Output: mount error: could not resolve address for saausnprddevotm
.file.core.windows.net: Unknown error
```

as you can see above there is a new line between `saausnprddevotm` and the azure domain `.file.core.windows.net`. In the secret I have checked that there aren't any new line characters, and there definitely is not. Below is the YAML for the secret:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: asa-otm
  labels:
    app: my-app
    role: secret
    env: dev
type: Opaque
data:
  azurestorageaccountname: c2FhdXNucHJkZGV2b3RtCg==
  azurestorageaccountkey: PASSWORD  
```

Have also raise this in [kubernetes #63326](https://github.com/kubernetes/kubernetes/issues/63326)
