### ISSUE TITLE
Auto Scaling did not scale down

### ISSUE THREAD

**Issue by beaudryj** [Azure/acs-engine#3110]
**Is this a request for help?**: Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**:  516e6ba41c71769d43504429170d02e4fc1349cb (havent rebuilt cluster in a while trying to stick with a build for a bit)

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** : Kubernetes 1.10.2 

**What happened**: VM Autoscaler Addon did not scale down, scaled up nicely though 💯 

**What you expected to happen**: I expected my killed workload to scale the clusterdown

**How to reproduce it** (as minimally and precisely as possible): 
I threw this at my cluster and it scaled up to 9, then I deleted it about 10 minutes later expecting it to scale down and sat and watched for about another 10 minutes. Checked the Autoscaler log and a saw that it flagged 7 nodes not being needed but it never did anything about it. 
``` 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx0-deployment
  labels:
    app: nginx0-deployment
spec:
  replicas: 25
  template:
    metadata:
      labels:
        app: nginx0
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx:1.7.9
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "1"
```
