### ISSUE TITLE
Node labels don't get applied to Windows nodes

### ISSUE THREAD

**Issue by bnookala** [Azure/acs-engine#3266]
**Is this a request for help?**:

No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

---

**What version of acs-engine?**:

acs-engine-v0.18.1-darwin-amd64, but I suspect all.

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:

Deploy a hybrid cluster with custom node labels on linux pools and windows pools, noticed that the custom node labels don't get applied to the windows nodes, and is in fact, missing many node labels altogether.

Linux pool:

```yaml
labels:
      agentpool: linuxpool
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/instance-type: Standard_DS2_v2
      beta.kubernetes.io/os: linux
      failure-domain.beta.kubernetes.io/region: australiaeast
      failure-domain.beta.kubernetes.io/zone: "0"
      kubernetes.azure.com/cluster: wow-dev-k8sHack-aae2
      kubernetes.io/hostname: k8s-linuxpool-20427215-0
      kubernetes.io/role: agent
      storageprofile: managed
      storagetier: Premium_LRS
```

Windows pool:

```yaml
labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/instance-type: Standard_DS2_v2
      beta.kubernetes.io/os: windows
      failure-domain.beta.kubernetes.io/region: australiaeast
      failure-domain.beta.kubernetes.io/zone: "0"
      kubernetes.io/hostname: 20427k8s9010
```

**What you expected to happen**:

The custom node labels should apply to the windows nodes.

**How to reproduce it** (as minimally and precisely as possible):

Add custom labels to a windows agent pool (or don't - it doesn't appear to add them regardless):

```
    "agentPoolProfiles": [
      {
        "name": "windowsPooll",
        "count": 3,
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Windows"
        "customNodeLabels": {
          "bar": "lulz",
          "baz": "foo"
        }
      }
    ],
```

**Anything else we need to know**:

Seems like this is the problematic line: https://github.com/Azure/acs-engine/blob/d9bd63bf0592fbed9dd9b2cf40b9725bc8b9e0c0/parts/k8s/kuberneteswindowssetup.ps1#L47
