### ISSUE TITLE
Access to API Controller in private vnet

### ISSUE THREAD

**Issue by aminebizid** [Azure/acs-engine#3317]
**Is this a request for help?**:
YES
**What version of acs-engine?**:
Latest on master
**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes v1.11.0-beta.2

**Context**
I'm running K8S on a private vnet using a jumpbox.
I created this SVC to give external access to kube-apiserver

```yaml
apiVersion: v1
kind: Service
metadata:
 name: kube-apiserver
 namespace: kube-system
spec:
 type: LoadBalancer
 ports:
  - port: 443
 selector:
  component: kube-apiserver
```

**Issue**
Now when trying kubectl from my laptop, I get this error: 
```bash
Unable to connect to the server: x509: certificate is valid for 10.255.255.5, 10.255.255.15, 10.0.0.1, not 104.40.30.12
```
**Workaround**
I use this alias as workaround:
```bash
alias k='kubectl --insecure-skip-tls-verify '
```
**Question**

Any better idea please. Like ssh -L or whatever

Thanks
