### ISSUE TITLE
ARM_CLOUD is not passed down to autoscaler

### ISSUE THREAD

**Issue by gsacavdm** [Azure/acs-engine#3445]
**Is this a request for help?**: No
---
**Is this an ISSUE or FEATURE REQUEST?**: Issue
---
**What version of acs-engine?**: v0.19.1
---
**Orchestrator and version**: Kubernetes v1.10

**What happened**: Deployed Kubernetes  v1.10 with autoscaler enabled to Azure Government. The deployment succeeded but the autoscaler pod is stuck in `CrashLoopBackOff` with the following error:

> I0707 19:39:33.629243       1 cloud_provider_builder.go:72] Building azure cloud provider.
I0707 19:39:33.727332       1 cloud_provider_builder.go:158] Creating Azure Manager with default configuration.
I0707 19:39:33.727442       1 azure_manager.go:163] Starting azure manager with subscription ID "876b395f-65a1-409c-935a-3c3ff4e13005"
I0707 19:39:33.727511       1 azure_client.go:305] azure: using client_id+client_secret to retrieve access token
E0707 19:39:36.784181       1 azure_scale_set.go:199] VirtualMachineScaleSetVMsClient.List failed for k8s-sacak8ag-96121586-vmss: compute.VirtualMachineScaleSetVMsClient#List: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription 'XXXXXX' could not be found."
F0707 19:39:36.784360       1 cloud_provider_builder.go:162] Failed to create Azure Manager: compute.VirtualMachineScaleSetVMsClient#List: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription 'XXXXXX' could not be found."

**What you expected to happen**:
The autoscaler should run without errors and successfully scale up/down nodes as needed.

**How to reproduce it** (as minimally and precisely as possible):
Deploy to Azure Government the following:

```yaml
   "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.10",
      "kubernetesConfig": {
        "useAksExtension": false,
        "addons": [
          {
            "name": "cluster-autoscaler",
            "enabled": true,
            "config": {
              "minNodes": "1",
              "maxNodes": "5"
            }
          }
        ]
      }
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "test-k8",
      "vmSize": "Standard_D3_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "testagents",
        "count": 3,
        "vmSize": "Standard_D3_v2",
        "availabilityProfile": "VirtualMachineScaleSets"
      }
    ],
```

**Anything else we need to know**:
This is happening because the Azure Cloud (Azure Goverment, Azure China, etc) is not being passed down to the autoscaler in the `ARM_CLOUD` environment variable where [it expects it](https://github.com/kubernetes/autoscaler/blob/a37aa1c4aaa2cc3d6db5d04e268df7438b93cb1e/cluster-autoscaler/cloudprovider/azure/azure_manager.go#L111).
