### ISSUE TITLE
AzureGermanCloud: Error while creating Azure Resources (PVC, LB) -- Confidential Client is not supported in Cross Cloud

### ISSUE THREAD

**Issue by ashishkulk** [Azure/acs-engine#3488]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
0.18.9
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.10

**What happened**:
Tried to create pvc. 
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-storage
  labels:
    app: pvc-storage
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "64Gi"
  storageClassName: "managed-premium"
```
PVC is always in _Pending State_
Recieved error : **Confidential Client is not supported in Cross Cloud**
```
Warning   ProvisioningFailed   persistentvolume-controller   Failed to provision volume with StorageClass "managed-premium": azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxxxx/resourceGroups/test34/providers/Microsoft.Compute/disks/Test34-d-pvc-2347c071-8998-11e8-ade1-0017fa105e49?api-version=2016-04-30-preview: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"AADSTS90038: Confidential Client is not supported in Cross Cloud request.\r\nTrace ID: xxxx\r\nCorrelation ID: xxxx\r\nTimestamp: 2018-07-17 08:05:35Z","error_codes":[90038],"timestamp":"2018-07-17 08:05:35Z","trace_id":"xxxxx","correlation_id":"xxxxx"}
```

**What you expected to happen**:
PVC should get created.

**How to reproduce it** (as minimally and precisely as possible):
Deploy on AzureGermanCloud

**Anything else we need to know**:
Also tested on 0.17.1 with 1.10 k8 , 0.16.1 with 1.8 k8. Same results.
Tried changing Service Principals too.
