### ISSUE TITLE
Update azure-cloud-provider rolebinding

### ISSUE THREAD

**Issue by feiskyer** [Azure/acs-engine#3847]
**Is this a request for help?**:

A placeholder for updating cluster role azure-cloud-provider and binding. This is required for https://github.com/kubernetes/kubernetes/pull/68212.

```yaml
kind: List
apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    labels:
      kubernetes.io/cluster-service: "true"
    name: system:azure-cloud-provider
  rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs:
    - create
    - patch
    - update
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
    - get
    - create
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    labels:
      kubernetes.io/cluster-service: "true"
    name: system:azure-cloud-provider
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:azure-cloud-provider
  subjects:
  - kind: ServiceAccount
    name: azure-cloud-provider
    namespace: kube-system
  - kind: ServiceAccount
    name: persistent-volume-binder
    namespace: kube-system
```
