### ISSUE TITLE
Create option to deactivate Unattended-Upgrade

### ISSUE THREAD

**Issue by denniszielke** [Azure/acs-engine#4115]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

**What version of acs-engine?**:
All
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
By default all vms are set to use automatic updates. https://help.ubuntu.com/lts/serverguide/automatic-updates.html.en 
We would like to have an option that allows us to deactivate this since for some cases we are not yet ready to move to the next kernel version.

**What you expected to happen**:
If the value of 
`APT::Periodic::Unattended-Upgrade "1"; `
and 
`APT::Periodic::Update-Package-Lists "1";`
 is set in  
`/etc/apt/apt.conf.d/20auto-upgrades`  
then automatic updates will happen.

**How to reproduce it** (as minimally and precisely as possible):
Let the vm run and it will update eventually - that is expected. 

**Anything else we need to know**:
We are using for the following daemonset to deactivate unattened upgrades on all vms.
This script in a configmap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: set-upgrade-script
data:
  run.sh: |
    #!/bin/sh

    echo "reading upgrade config"
    less /config

    # Deactivate upgrades
    sed -e 's/Update-Package-Lists "1"/Update-Package-Lists "0"/ ; s/Unattended-Upgrade "1"/Unattended-Upgrade "0"/' /config > /config_out
    # Activate upgrades
    #sed -e 's/Update-Package-Lists "0"/Update-Package-Lists "1"/ ; s/Unattended-Upgrade "0"/Unattended-Upgrade "1"/' /config > /config_out

    cat /config_out > /config

    echo "new config:"

    less /config

    exit 0
```
This daemonset using the script
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: set-upgrade-daemon
  labels:
    app: set-upgrade-daemon
spec:
  template:
    metadata:
      labels:
        name: set-upgrade-daemon
    spec:
      containers:
        - name: set-upgrade-daemon
          securityContext:
            privileged: true
          image: alpine
          imagePullPolicy: Always
          command:
          - /bin/sh
          - -c
          - |
            echo "copy scripts to /tmp"
            cp /scripts/*.sh /tmp
            echo "chmod"
            chmod +x /tmp/run.sh
            echo "execute"
            /tmp/run.sh
          resources:
            requests:
              cpu: 5m
              memory: 50Mi
          volumeMounts:
          - mountPath: /scripts
            name: scripts
          - mountPath: /config
            name: upgradeconfig
            readOnly: false
      volumes:
      - name: scripts
        configMap:
          name: set-upgrade-script
      - name: upgradeconfig
        hostPath:
          path: /etc/apt/apt.conf.d/20auto-upgrades
          type: File
```
