### ISSUE TITLE
Unable to run deployment when defining requests cpu quota

### ISSUE THREAD

**Issue by mfaizanse** [Azure/acs-engine#413]
Hi, I have a deployed a win + k8s cluster using acs-engine with 2 agent nodes.

When I deploy a pod without any requests parameter, it works.
`kubectl run iis2 --image microsoft/iis   --expose --port=80`

But when I run with requests parameter, if fails on ErrPullImage.
`kubectl run iis2 --image microsoft/iis --requests cpu=50m  --expose --port=80`
I have tried with CPU 5m, 10m, 50m, 100m, 200m, 300m, 500m. And also I have tried with my own asp.net win container image as well.
![pasted_image_at_2017_03_15_05_35_pm](https://cloud.githubusercontent.com/assets/9897945/23985459/069a4a18-0a41-11e7-8621-cbfc2657c991.png)

Actually, I want to try the [Horizontal Pod Autoscaling](https://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/walkthrough/). I have tried the hpa on iis deployment without the requests parameter, but the hpa gives error:
 `unable to get metrics for resource cpu: no metrics returned from heapster`
I am not sure whether the requests parameter will solve this or not.
![222](https://cloud.githubusercontent.com/assets/9897945/23985856/19bfa474-0a43-11e7-9ee6-742aba94d62d.PNG)

I have rdp to the agent and tried docker stats and it returned:
`Template parsing error: template: :1: unexpected "{" in command`

Let me know if I am missing anything here.

**Comment by mfaizanse** [comment]
Is this issue related to acs or kubernetes as its also mentioned in the kubernetes git - [link](https://github.com/kubernetes/heapster/issues/1433)

**Comment by mfaizanse** [comment]
I have tried using yaml file:
```
apiVersion: v1
kind: Service
metadata:
  name: win-webserver
  labels:
    app: win-webserver
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: win-webserver
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: win-webserver
  name: win-webserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: win-webserver
      name: win-webserver
    spec:
      containers:
      - name: windowswebserver
        image: mfaizanbentley/containertest
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            cpu: 1
            memory: 128Mi
        
      nodeSelector:
        beta.kubernetes.io/os: windows
```

But it says:
`fit failure summary on nodes : Insufficient cpu (2), Insufficient memory (2), MatchNodeSelector (1)`

![3333](https://cloud.githubusercontent.com/assets/9897945/23995129/022bf49e-0a6a-11e7-8acb-7f4e0163d6f1.PNG)

I have tried with requests - cpu = 50m as well but same issue.
Is there any way to find available cpu/resources of a node?
