### ISSUE TITLE
[Kubernetes] Support setting the DNS name label for public IPs created by ingress controllers

### ISSUE THREAD

**Issue by rocketraman** [Azure/acs-engine#517]
When deploying an ingress controller, Azure Kubernetes helpfully creates a public IP address.

It would be useful to set the "DNS name label" of the created IP address based on an annotation in the Deployment. CNAMEs can then be used to point to this Azure DNS name, resulting in a (more) stable DNS configuration if the ingress controller is deleted and recreated.

**Comment by JackQuincy** [comment]
Agreed, this is actually an upstream issue on Kubernetes. Could you also file an issue there https://github.com/kubernetes/kubernetes .

**Comment by tomerf** [comment]
I am interested the same feature. I was looking into it but I can't find an option to set the "DNS name label" using the Azure API. Can anyone confirm it is missing?

**Comment by christianse2** [comment]
Yes this is really needed. I see the upstream issue is near merge.

**Comment by tomerf** [comment]
You're welcome!
I upgraded my cluster this week and AKS currently support 1.8.X. Are you using acs-engine directly to deploy?

**Comment by dtzar** [comment]
yes, I'm using ACS-engine to deploy

**Comment by efirdman** [comment]
So, guys.
Is it possible to set DNS name of Public IP? 
If yes - please drop a sample yaml.

Using Azure Kubernetes version 1.9.6

**Comment by tomerf** [comment]
Yes, it's supported since 1.9.0
```
apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    name: my-svc
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: svc-name
spec:
  ...
```
And when it's created it will be accessible as svc-name.azure-region.cloudapp.azure.com
