### ISSUE TITLE
Error when creating kubernetes cluster using networkpolicy `azure`

### ISSUE THREAD

**Issue by wangtt03** [Azure/acs-engine#564]
repo steps:
1. create kubernetes cluster using networkpolicy `azure`
    ```
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "KubernetesConfig":{
        "NetworkPolicy":"azure"
      },
      "orchestratorVersion": "1.6.2"
    },
    ```
2. login to created kubernetes cluster.
3. run `kubectl run nginx --image=nginx --replicas=1`
4. run `kubectl expose deployment nginx --port=80`
5. run `kubectl annotate ns default "net.beta.kubernetes.io/network-policy={\"ingress\": {\"isolation\": \"DefaultDeny\"}}"`
6. create file `nginx-policy.yaml` with content:
    ```
    kind: NetworkPolicy
    apiVersion: extensions/v1beta1
    metadata:
      name: access-nginx
    spec:
      podSelector:
        matchLabels:
          run: nginx
      ingress:
        - from:
          - podSelector:
              matchLabels:
                access: "true"
    ```
7. run `kubectl create -f nginx-policy.yaml`
8. run `kubectl run busybox --rm -ti --image=busybox /bin/sh`
9. run `wget --spider --timeout=1 nginx`

expected:
wget timeout.

actual:
connected.
