### ISSUE TITLE
Unable to get kubernetes pods to access the database

### ISSUE THREAD

**Issue by narasi** [Azure/acs-engine#675]
Hi, I have been trying to setup a kubernetes cluster with the help of the Azure Container Service. After reading up on documentation and best practices, I have written a yaml file that sets up the cluster for me, but unfortunately the pods cannot reach the database cluster, which is however accessible from the kubernetes host.

**Is this a request for help?**:
Yes
---

Here is a copy of the representative yaml file for the kubernetes cluster

```
---
# First, declaring the storage credentials
apiVersion: v1
kind: Secret
metadata:
  name: storagesecret
type: Opaque
data:
  azurestorageaccountname: dummy
  azurestorageaccountkey: dummy

---
# The actual deployment of the dockerised drupal instance is declared here
# Externalities are :
#                   1. Shared volume for assets
# @TODO             2. Config map for the database credentials
# @TODO             3. Shared volume for soure code
# @TODO             4. Persistent Volumes for #3
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8sdrupal
  labels:
    name: k8sdrupal1
spec:
  replicas: 1
  template:
    metadata:
      name: drupalcontainer
      labels:
        name: drupal8
    spec:
      imagePullSecrets:
        - name: gbregsecret
      volumes:
        - name: labelassetsdefault
          azureFile:
            secretName: storagesecret
            shareName: assetsdefault
            readOnly: false
        - name: labelassetssingapore
          azureFile:
            secretName: storagesecret
            shareName: assetssingapore
            readOnly: false
        - name: labelassetsthailand
          azureFile:
            secretName: storagesecret
            shareName: assetsthailand
            readOnly: false
      containers:
        - name: dummy
          image: dummy
          ports:
            - containerPort: 80
          env:
            -
              name: HTTP_HOST
              value: dummy
            -
              name: DATABASE
              value: dummy
            -
              name: DATABASE_USERNAME
              value: dummy
            -
              name: DATABASE_PASSWORD
              value: dummy
            -
              name: DATABASE_HOST
              value: mysqlcluster
          volumeMounts:
            - mountPath: /app/web/sites/default
              name: labelassetsdefault
            - mountPath: /app/web/sites/singapore
              name: labelassetssingapore
            - mountPath: /app/web/sites/thailand
              name: labelassetsthailand

---
# Declaration for the mysql service that connects to the mysql cluster
kind: Service
apiVersion: v1
metadata:
  name: mysqlcluster
  labels:
    name: k8sdrupal1
spec:
  ports:
    -
      name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 0

---
# Endpoint for the mysql service, has the config for connecting to the database cluster
kind: Endpoints
apiVersion: v1
metadata:
  name: mysqlcluster
subsets:
  -
    addresses:
      -
        ip: dummy
    ports:
      -
        port: 3306
        name: mysql

---
# Finally, we arrive at the service that maps the drupal containers
kind: Service
apiVersion: v1
metadata:
  name: k8sdrupal
  labels:
    name: k8sdrupal1
spec:
  ports:
    -
      port: 80
      protocol: TCP
      targetPort: 80
      name: http
    -
      port: 3306
      protocol: TCP
      targetPort: 3306
      name: mysql
  selector:
    name: drupal8
  type: LoadBalancer

```
Here is also the representative Dockerfile which is used to the container used in the cluster above
```
# Obtain the base image OS
FROM ubuntu:16.04

# Declare the working directory
WORKDIR /app

# Get the latest package information and apply any available patches
RUN apt-get update 

# Install the necessary services
RUN apt-get -y install curl \
 						php7.0 \
 						apache2 \
  						git \
						mysql-client

# Now the necessary support applications
RUN apt-get -y install \
				php7.0-cli \
				php7.0-mbstring \
				php7.0-mysql \
				php7.0-gd \
				php7.0-xml \
				php7.0-zip \
				php7.0-curl \
				libapache2-mod-php7.0 \
				lynx-cur

# Then composer
# @TODO : Replace this line with a more robust way to install composer
RUN curl -sS https://getcomposer.org/installer | php

RUN a2enmod php7.0
RUN a2enmod rewrite
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

EXPOSE 80

RUN a2ensite 000-default

# ALL SET!
CMD /usr/sbin/apache2ctl -D FOREGROUND
```

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Once the cluster was setup with the above structure, the pods could not access the database on Azure. I have been lost in iptables, cidr flags etc but none of those seem to help, I feel there is something I am missing out on here that I cannot easily put my finger on. Do note that from the host machine on where we run kubernetes, the database cluster is accessible.

**How to reproduce it** (as minimally and precisely as possible):
Setup a cluster based on the docker image using the dockerfile and the kubernetes yaml file mentioned in this case. Try hitting any mysql host that is setup on a machine other than the kubernetes host.

Any help will be much appreciated. I have been banging my head on this issue for days now
