### ISSUE TITLE
Kubernetes deployed with non-working system service

### ISSUE THREAD

**Issue by ppanyukov** [Azure/acs-engine#734]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:

- Deployed with `az acs create --orchestrator-type Kubernetes` on 07 June 2017.

- See `kube-system` service `heapster-v1.2.0` failed to start.

- Error message says: `invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"exec: \\\\\\\"/heapster\\\\\\\": stat /heapster: no such file or directory\\\"\\n\"`

- Looking at the deployment manifest, looks like this service is configured with the wrong image:

```
    spec:
      containers:
      - command:
        - /heapster
        - --source=kubernetes.summary_api:""
        image: gcrio.azureedge.net/google_containers/exechealthz-amd64:1.2
```

- Looks like the image should be: either `gcr.io/google_containers/heapster:v1.2.0` or `gcr.io/google_containers/heapster-amd64:v1.3.0`

- Trying to edit the deployment to correct the image has no effect: everything reverts back to the original `exechealthz-amd64:1.2` no matter what I try.

**What you expected to happen**:

System services should operate without errors on deployment.

**How to reproduce it** (as minimally and precisely as possible):

Run the `az` command.

**Anything else we need to know**:
