### ISSUE TITLE
Azure Load Balancer -- Session Affinity Support

### ISSUE THREAD

**Issue by lachie83** [Azure/acs-engine#738]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature Request

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:

Azure ACS Engine currently doesn't support Session Affinity for TCP Connections. Session affinity support is needed for application layer protocols like Websocket, MQTT, or any other protocols requiring persistent connections/sticky sessions. This will be used for protocol gateways (plugins) we will deploy as containers. When given a sample Kubernetes Service Configuration below:

```
---
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    name: test
spec:
  type: LoadBalancer
  sessionAffinity: "ClientIP"
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
   name: test
```

**What you expected to happen**:

An Azure Load Balancer created with Session persistence set to ClientIP

**How to reproduce it** (as minimally and precisely as possible):

Deploy the service above then config in the Azure Portal that session persistence has not been set.

**Anything else we need to know**:
