### ISSUE TITLE
Kubernetes Service loadBalancerSourceRanges only creates first rule in list

### ISSUE THREAD

**Issue by lachie83** [Azure/acs-engine#739]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:
Azure ACS Engine has support for the loadBalancerSourceRanges annotation but has a bug where only one rule is applied even when you specify multiple IP Whitelist rules. When given a sample Kubernetes Service Configuration below:

```
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    name: test
spec:
  type: LoadBalancer
  sessionAffinity: "ClientIP"
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
   name: test
  loadBalancerSourceRanges:
    - 1.1.1.0/24
    - 2.2.2.0/24
```

**What you expected to happen**:

A corresponding rule is created for each source range in the list. Only the first is being created.

**How to reproduce it** (as minimally and precisely as possible):

Create the service above.

**Anything else we need to know**:
